---
- name: Install and configure Apache2
  hosts: localhost
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
    - name: Install Apache2
      apt:
        name: apache2
        state: present/
      notify: restart apache
    - name: Start and enable Apache
      service:
        name: apache2
        state: started
        enabled: yes
    - name: Create custom homepage
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <body>
          <h1>Ansible project </h1>
          <p>Deployed successfully!</p>
          </body>
          </html>
        owner: root
        group: root
        mode: "0644"
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted

